# Generated by Django 6.0.4 on 2026-04-20 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(default='Mahima Life Sciences Pvt Ltd', max_length=255)),
                ('account_no', models.CharField(default='MLSP96', max_length=100)),
                ('bank_name', models.CharField(default='HDFC Bank Ltd.', max_length=255)),
                ('branch_name', models.CharField(default='Rohini Sector 9 – Northex Mall – New Delhi, Delhi', max_length=255)),
                ('ifsc_code', models.CharField(default='HDFC0001347', max_length=50)),
                ('email_sender_name', models.CharField(default='Mahima Life Sciences', help_text='Company name for email and WhatsApp signature', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_sales_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('item_sales_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('item_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('item_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_term', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_due_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('overdue_days', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-invoice_due_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('signup_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
