# Generated by Django 6.0.4 on 2026-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_loanapplication_deleted_at_loanapplication_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_sales_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('item_sales_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('item_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('item_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_term', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_due_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('overdue_days', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.CharField(blank=True, max_length=150, null=True)),
                ('archive_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Permanent Saved Record',
                'verbose_name_plural': 'Permanent Saved Records',
                'ordering': ['-archived_at'],
            },
        ),
    ]
