# Generated by Django 6.0.4 on 2026-04-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_loanapplicationarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Size in KB')),
                ('total_records', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Excel Batch',
                'verbose_name_plural': 'Excel Batches',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='loanapplicationarchive',
            options={'ordering': ['-archived_at', 'batch_number']},
        ),
        migrations.RemoveField(
            model_name='loanapplicationarchive',
            name='archive_reason',
        ),
        migrations.RemoveField(
            model_name='loanapplicationarchive',
            name='original_id',
        ),
        migrations.AddField(
            model_name='loanapplicationarchive',
            name='batch_number',
            field=models.IntegerField(blank=True, help_text='Batch sequence number', null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationarchive',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='notifications.excelbatch'),
        ),
        migrations.AddIndex(
            model_name='loanapplicationarchive',
            index=models.Index(fields=['batch', 'batch_number'], name='notificatio_batch_i_c609e5_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplicationarchive',
            index=models.Index(fields=['customer_name'], name='notificatio_custome_6ed844_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplicationarchive',
            index=models.Index(fields=['invoice_no'], name='notificatio_invoice_034c46_idx'),
        ),
    ]
