# Generated by Django 6.0.3 on 2026-05-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_excelbatch_alter_loanapplicationarchive_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='company',
            field=models.CharField(choices=[('Mahima', 'Mahima Life Sciences Pvt Ltd'), ('Vincit', 'Vincit Labs Pvt Ltd')], db_index=True, default='Mahima', max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplicationarchive',
            name='company',
            field=models.CharField(choices=[('Mahima', 'Mahima Life Sciences Pvt Ltd'), ('Vincit', 'Vincit Labs Pvt Ltd')], db_index=True, default='Mahima', max_length=50),
        ),
    ]
