# Generated by Django 6.0.3 on 2026-05-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_loanapplication_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationarchive',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
