# Generated by Django 6.0.3 on 2026-05-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_loanapplication_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='email_message_id',
            field=models.CharField(blank=True, help_text='Last email Message-ID for threading replies in same conversation', max_length=255, null=True),
        ),
    ]
