# Generated by Django 6.0.4 on 2026-05-30 05:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_loanapplication_email_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('PTP', 'Promise to Pay (PTP)'), ('Other', 'Other')], default='Call', max_length=50)),
                ('followup_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('ptp_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ptp_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='notifications.loanapplication')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-followup_date', '-created_at'],
            },
        ),
    ]
