# Generated by Django 6.0.5 on 2026-06-06 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_followup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('morning_time', models.TimeField(default='10:00')),
                ('evening_time', models.TimeField(default='18:00')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays Only'), ('custom', 'Custom Days')], default='daily', max_length=20)),
                ('custom_days', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_notifications', models.IntegerField(default=0)),
                ('filter_companies', models.CharField(blank=True, max_length=500, null=True)),
                ('filter_min_overdue', models.IntegerField(default=0)),
                ('filter_max_overdue', models.IntegerField(default=999)),
                ('filter_payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('morning_message_template', models.TextField(blank=True, null=True)),
                ('evening_message_template', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('time_slot', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('message_sent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.loanapplication')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationschedule')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
