# Generated by Django 6.0.5 on 2026-06-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notificationschedule_schedulednotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulednotification',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedulednotification',
            name='application',
        ),
        migrations.DeleteModel(
            name='NotificationSchedule',
        ),
        migrations.DeleteModel(
            name='ScheduledNotification',
        ),
    ]
